### ISSUE TITLE
[Feature] - Filter by chest material type

### ISSUE THREAD

**Issue by dustinlacewell** [sbtoonz/CFC#1]
It'd be handy if there was a configuration option to allow specifying what kinds of chests to draw from. For example, only drawing from wooden chests, etc.

**Comment by sbtoonz** [comment]
This could feasibly be added

**Comment by sbtoonz** [comment]
![image](https://github.com/sbtoonz/CFC/assets/67915879/6bee67ad-65ec-40ed-ad63-ec20bb7a4589)
I am envisioning something like this

**Comment by sbtoonz** [comment]
https://cdn.discordapp.com/attachments/1094717823630180442/1106993603001204827/Valheim_2023-05-13_10-16-04.mp4

**Comment by sbtoonz** [comment]
[https://cdn.discordapp.com/attachments/830502805869559848/1107046237288538243/Valheim_2023-05-13_13-41-18.mp4](url)

**Comment by sbtoonz** [comment]
Feature complete
