### ISSUE TITLE
[Feature] - Pull from 'Item Drawers' mod in addition to Chests

### ISSUE THREAD

**Issue by justinglavin** [sbtoonz/CFC#3]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow the player to build/craft using items that are stored in Item Drawers as well as chests
Item Drawers: https://valheim.thunderstore.io/package/makail/ItemDrawers/

**Comment by sbtoonz** [comment]
> **Is your feature request related to a problem? Please describe.** No
> 
> **Describe the solution you'd like** Allow the player to build/craft using items that are stored in Item Drawers as well as chests Item Drawers: https://valheim.thunderstore.io/package/makail/ItemDrawers/

Let me take a look at how item drawers works again and see if this is feasible

It should be something I can include in an upcoming release
