### ISSUE TITLE
[BUG] - Mill and Wheel increase loot

### ISSUE THREAD

**Issue by lucastucious** [sbtoonz/CFC#6]
**Describe the bug**
i have a weird bug with this mod. Mill and Wheel automatically pull Barley and Flax from container (i guess ?) and more importantly, it seems to duplicate items. One flax can make 23 line thread...

**Comment by sbtoonz** [comment]
Lol how did I forget these two items 

I'll update

**Comment by sbtoonz** [comment]
e97f4a1

**Comment by sbtoonz** [comment]
Solved in v1.1.0

**Comment by lucastucious** [comment]
Hi there ! 
Spinning weel and mill still multiply loot.
One flax make 16 linen thread...

**Comment by sbtoonz** [comment]
Will fix

**Comment by sbtoonz** [comment]
[sbtoonz-Craft_From_Containers_Redux-1.1.1.zip](https://github.com/sbtoonz/CFC/files/12003011/sbtoonz-Craft_From_Containers_Redux-1.1.1.zip)
Can you please test this version and report back? It is working on my end but would like validation this time around

**Comment by lucastucious** [comment]
One more : 
All crafters will refuel with any chest that aren't "none". Filtering seems to not apply anymore

**Comment by sbtoonz** [comment]
> One more : 
> 
> All crafters will refuel and searching for ore with any chest that aren't "none". Filtering seems to not apply anymore. Should i create a separate issue ?

Please 

I did solve the default name thing but this new issue arose in squashing this bug :) 

So I would like to track it in its own issue please
